name: number_trivia
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  equatable: ^2.0.5
  dio: ^5.4.0
  dartz: ^0.10.1
  isar: ^3.1.0+1
  internet_connection_checker: ^1.0.0+1
  path_provider: ^2.1.1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  http_mock_adapter: ^0.6.1
  isar_generator: ^3.1.0+1
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
